Fix: AWS image owners type (#49)
Issue:
Image owner is defined as owner: 099720109477 but 0 is dropped as shown in the following error message.
Error: reading EC2 AMIs: InvalidUserID.Malformed: Invalid user id: "99720109477"

Cause:
owner is of type number

Fix:
owner in specification changed to type string