Version bump - v1.0.1
Cherry-picked commit hash: 6fd6023b917cc78c60f3236ab4bf2b0deaa557d7
Fix: AWS image owners type (#49)

Issue:
Image owner is defined as owner: 099720109477 but 0 is dropped as shown in the following error message.
Error: reading EC2 AMIs: InvalidUserID.Malformed: Invalid user id: "99720109477"

Cause:
owner is of type number

Fix:
owner in specification changed to type string