Fix: use of PyYAML 'safe_load' instead of 'CLoader' (#42)
Issue:
When manual install is skipped, the virtual environment might fail to detect `libyaml`, `CLoader` is then not available within `PyYAML` and fails with an `ImportError` if `CLoader` is imported.

Error message - `ERROR: could not read file /home/user/Projects/edb-terraform/infrastructure-examples/aws-all.yml (module 'yaml' has no attribute 'CLoader')`
Ref: https://github.com/yaml/pyyaml/issues/108

Fix:
Use `safe_load` instead of using `CLoader`, which depends on `libyaml` and might require a manual install with the use of `python setup.py --with-libyaml install` when using python virtual environments.

Other Changes:
* Removed unused `security_group_ids` variable from AWS modules root variable file
* added `ImportError` to `try/except` import