FIX: edb-terraform cli - update generate_terraform function with a default for 'infra_template_variables'
---

Error:
$ edb-terraform terraform docs/examples/aws/biganimal.yml -c aws
Traceback (most recent call last):
  File "/home/user/.local/bin/edb-terraform", line 8, in <module>
    sys.exit(entry_point())
  File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 24, in entry_point
    main()
  File "/home/user/.local/lib/python3.10/site-packages/edbterraform/__main__.py", line 17, in main
    outputs = arg_parser.process_args()
  File "/home/user/.local/lib/python3.10/site-packages/edbterraform/args.py", line 540, in process_args
    outputs = generate_terraform(
TypeError: generate_terraform() missing 1 required positional argument: 'infra_template_variables'